/* This file generated by constants/tables.py */

#ifndef TABLES_H
#define TABLES_H
extern const float tables_delta_time_free[];
#define TABLES_DELTA_TIME_FREE_LEN 65
extern const float tables_swing_pts[];
#define TABLES_SWING_PTS_LOOKUP(n,x1,x2) \
   do { \
       *x1 = tables_swing_pts[(2) * (n)]; \
       *x2 = tables_swing_pts[(2) * (n) + 1]; \
   } while (0)
#define TABLES_N_SWING_SETS 9
#define TABLES_SWING_SET_SIZE 2
#endif /* TABLES_H */
