#!/bin/bash
# Plays a sine wave on the right channel of the given AUDIODEV
if [[ -z "$1" ]]
then
    FREQ=440
else
    FREQ="$1"
fi
export AUDIODEV=plughw:CARD=Pro,DEV=0
sox --combine merge "|sox -n -c 1 -p synth sine 1 gain -200"\
    "|sox -n -c 1 -p synth sine ${FREQ}" -d
