#! /bin/bash
# Script for sending a control change message

if [ -z ${MIDIDEV} ]
then
    MIDIDEV=hw:1,0,0
fi

if [ -z ${MIDI_CHANNEL} ]
then
    MIDI_CHANNEL=0
fi

if [[ -z "$1" ]]
then
    CC=60
else
    CC=$1
fi

if [[ -z "$2" ]]
then
    VAL=100
else
    VAL=$2
fi


amidi -p $MIDIDEV -S `printf "b%x %02x %02x" $MIDI_CHANNEL $CC $VAL`  
