#! /bin/bash
if [ -z ${OPENOCD_INTERFACE} ]
then
    OPENOCD_INTERFACE=interface/stlink-v2.cfg
fi
if [ -z ${OPENOCD_BOARD} ]
then
    OPENOCD_BOARD=board/stm32f429discovery.cfg
fi
openocd -f ${OPENOCD_BOARD} \
    -f ${OPENOCD_INTERFACE}
