#! /bin/bash
if [ -z ${OPENOCD_INTERFACE} ]
then
    export OPENOCD_INTERFACE=interface/stlink-v2.cfg;
fi
sudo openocd -f /usr/local/share/openocd/scripts/board/stm32f429discovery.cfg \
    -f ${OPENOCD_INTERFACE}
