#!/bin/bash

if [ -z ${OPENOCD_INTERFACE} ]
then
    export OPENOCD_INTERFACE=interface/stlink-v2.cfg;
fi

if [ -z ${BOARD_VERSION} ]
then
    echo "Please define board version."
    exit -1
fi

trap on_sigint SIGINT

on_sigint() { kill -n 9 $! ; }

start_time=$(date +%s)

cat <<EOF

Welcome to the 856 for ZELLERSASN test.
Start test in SWITCH MODE.
(press Enter to continue)

EOF

read

if [ -z "$NO_FLASH_DEVICE"]; then
    if [ "$BOARD_VERSION" == BOARD_V2 ]; then

        cat <<EOF

Plug in all connections without power.
Then plug in power.
The device should be ready to flash via DFU.
(press Enter to continue)

EOF

        read

        CFLAGS=-DBOARD_V2\ -DCODEC_CS4270 make dfu_flash

        cat <<EOF

Unplug the USB, then power-cycle the device.
The device should now be ready to test.
(press Enter to continue)

EOF

        read

    else
        CFLAGS=-D${BOARD_VERSION} make flash
    fi
fi
make reset
sleep 2
scripts/test_switch.sh
make reset

cat<<EOF

Remove power.
Change to EXP MODE.
Apply power.
Now test ADC.
(press Enter to continue)

EOF
read

scripts/test_pot.sh

# Just test all LEDs at once
scripts/test_led.sh -1

#trap - SIGINT
# play_test_file seems to already trap sigint properly
#echo "Unplug USB."
scripts/play_random_file
scripts/test_midi_play_off

end_time=$(date +%s)
elapsed_time=$(( $end_time - $start_time ))
echo "Test took $(date --date=@$elapsed_time +%M\'%S\")"
