#! /bin/bash
# Script for testing MIDI functionality of turning playback off on 856

rm -f /tmp/test_midi_play_off_nums.XXX

# as amazing as this is, let's just write the CC and if it doesn't work, we check the CC
# arm-none-eabi-gdb --batch-silent \
#    -ex 'file ./main.elf' \
#    -ex 'set pagination off' \
#    -ex 'set logging file /tmp/test_midi_play_off_nums.XXX' \
#    -ex 'set logging on' \
#    -ex 'printf "%d\n", (int)synth_midi_cc_type_t_PLAY' \
#    -ex 'set logging off' \
#    -ex 'quit'

MIDIDEV=hw:1,0,0

MIDI_CHANNEL=0
#CC=$(cat /tmp/test_midi_play_off_nums.XXX)
CC=61

if [ "${BOARD_VERSION}" == BOARD_V2 ]; then
    # flush old receive
    amidi -p $MIDIDEV -d > /dev/null&
    sleep 0.1
    kill $!
    # launch midi receive
    rm -f /tmp/midithruresult.XXX
    amidi -p $MIDIDEV -d > /tmp/midithruresult.XXX&
fi

sleep 0.1

mididat=`printf "B%X %02X 00" $MIDI_CHANNEL $CC`  

amidi -p $MIDIDEV -S "$mididat"

sleep 0.1

if [ "${BOARD_VERSION}" == BOARD_V2 ]; then
    # check midi received correct data via midi thru
    kill $!
    sleep 0.1
    # hack with grep to remove blank lines
    midiresult="$(cat /tmp/midithruresult.XXX | grep -e '\S\+')"
    if [  "$midiresult" == "$mididat" ];
    then
        echo "MIDI thru PASSED"; 
    else
        echo "MIDI thru FAILED, received:"
        echo "$midiresult"
        echo "but sent"
        echo "$mididat"
    fi
    rm -f /tmp/midithruresult.XXX
fi
