#! /bin/bash
# Script for testing MIDI functionality on 856

MIDIDEV=hw:1,0,0

MIDI_CHANNEL=0
TOT_NUM_FUNS=67

for cc in `seq 0 $((TOT_NUM_FUNS-1))`
do
    echo "testing $cc"
    amidi -p $MIDIDEV -S `printf "b%x %02x 40" $MIDI_CHANNEL $cc`  
    sleep 1
done
