#!/bin/bash

if [ -z ${OPENOCD_INTERFACE} ]
then
    export OPENOCD_INTERFACE=interface/stlink-v2.cfg;
fi

if [ -z ${BOARD_VERSION} ]
then
    echo "Please define board version."
    exit -1
fi

trap on_sigint SIGINT

on_sigint() { kill -n 9 $! ; }

if [ "$BOARD_VERSION" == BOARD_V2 ]; then

    cat <<EOF
Plug in USB without power.
Then plug in power.
The device should be ready to flash via DFU.
(press Enter to continue)
EOF

    read

    CFLAGS=-DBOARD_V2\ -DCODEC_CS4270 make dfu_flash

    cat <<EOF
Unplug the USB, plug in the debugging connector for the subsequent steps.
(press Enter to continue)
EOF

    read

else
    CFLAGS=-D${BOARD_VERSION} make flash
fi
make reset
sleep 2
scripts/test_switch.sh
make reset
scripts/test_pot.sh
scripts/test_led.sh 0
scripts/test_led.sh 1
scripts/test_led.sh 2
scripts/test_led.sh 3
scripts/test_led.sh -1
trap - SIGINT
# play_test_file seems to already trap sigint properly
echo "Unplug USB."
scripts/play_test_file
scripts/test_midi_play_off

